# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  JavaScript: true

exclude_paths:
  - "config/**/*"
  - "script/*"
  - "package.json"
  - "Readme.md"
  - "Dockerfile"